### ISSUE TITLE
Install module as users

### ISSUE THREAD

**Issue by lb1f** [NoPurposeInLife/Sharepoint-Scripts#1]
https://github.com/NoPurposeInLife/Sharepoint-Scripts/blob/6816ddcf884a723d17a789930016cdbcdc1d2ef3/powershell_sharepoint_mass_check_in.ps1#L215

If you change this line from: Install-Module SharePointPnPPowerShellOnline

to: Install-Module SharePointPnPPowerShellOnline -Scope CurrentUser

It should allow the script to be executed as a standard user.

**Comment by NoPurposeInLife** [comment]
Patched, thanks!
